## 00. Pytorch

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8, 8, 8],
                       [9, 10, 11, 11],
                       [12, 12, 12, 12],
                       [20, 20, 20, 20]])
MATRIX

tensor([[ 7,  8,  8,  8],
        [ 9, 10, 11, 11],
        [12, 12, 12, 12],
        [20, 20, 20, 20]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12],
                        [13, 14, 15, 16]],
                       MATRIX])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[ 7,  8,  8,  8],
         [ 9, 10, 11, 11],
         [12, 12, 12, 12],
         [20, 20, 20, 20]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 4, 4])

In [ ]:
TENSOR[1]

tensor([[ 7,  8,  8,  8],
        [ 9, 10, 11, 11],
        [12, 12, 12, 12],
        [20, 20, 20, 20]])

### Random Tensors

```Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```

https://pytorch.org/docs/stable/generated/torch.rand.html#torch-rand


In [ ]:
# Create a random tesnors of size of shape  (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4186, 0.8921, 0.7118, 0.8597],
        [0.2055, 0.4422, 0.1484, 0.0997],
        [0.7102, 0.7143, 0.8663, 0.0332]])

In [ ]:
print(random_tensor.shape == TENSOR.shape)

False


In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
TENSOR_LIKE = torch.zeros_like(input=TENSOR)
TENSOR_LIKE

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 major key issue you might run into w/ PyTorch & deep learning (use tensor attributes)
1. Tensors wrong dtype - use `tensor.dtype`
2. Tensors wrong shape - use `tensor.shape`
3. Tensors wrong device - use `tensor.device`

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype=None,  # https://pytorch.org/docs/stable/tensors.html#data-types
                               device=None,          # What device is your tensor on https://pytorch.org/docs/stable/tensor_attributes.html?highlight=tensor+device#torch.device
                               requires_grad=False)  # whether or not to track gradients w/ this tensors operations
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [ ]:
int_32_tensor = torch.tensor([3, 5, 6], dtype=torch.int32)
int_32_tensor

tensor([3, 5, 6], dtype=torch.int32)

In [ ]:
product_of_tensors = int_32_tensor * float_16_tensor
product_of_tensors

tensor([ 9., 20., 30.], dtype=torch.float16)

In [ ]:
# Find details of tensor
print(product_of_tensors)
print(f"Datatype of tensor: {product_of_tensors.dtype}")
print(f"Shape of tensor: {product_of_tensors.shape}")
print(f"Device of tensor: {product_of_tensors.device}")

tensor([ 9., 20., 30.], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3])
Device of tensor: cpu


### Manipulating Tensors (operations)

Tensor operation include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing in neural networks and deep learning
1. Element-wise multiplication
2. Matrix multiplication (dot product)

https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are 2 main rules performing Matrix multiplication:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

http://matrixmultiplication.xyz/

In [ ]:
# Element-wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 892 µs, sys: 0 ns, total: 892 µs
Wall time: 904 µs


tensor(14)

In [ ]:
# Shapes for Matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [ ]:
# torch.mm() is an alias for torch.matmul()
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# To fix tensor shape issues use Transpose
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# The natrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimesnions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimesnions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
output_2 = torch.matmul(tensor_A.T, tensor_B)
output_2

tensor([[ 76, 103],
        [100, 136]])

## Finding the min, max, mean, sum, etc (tensor aggregations)

In [ ]:
# Creat a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the mean - note: torch.mean() requires a tensor of float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Find argmin() - returns index position of min value
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
# Find argmax()
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezzing and unsqueezing tensors

* Reshaping - reshapes an input tesbor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tesnors on top of each other (vstack) or side by side (hstack)
* Squezze - removes all `1` dimensions from a tensor
* Unaqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input w/ dimensions permuted (swapped) is a certain way

In [ ]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory with the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Squeeze - removes all single dimensions from a target tensor
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimesnion from x_reshaped
x_squeezed = torch.squeeze(x)
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# Unsqueeze - adds a single dimension to a target tensor at a specific dimension (dim)
print(f"Previous target : {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimesnion from x_reshaped
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# Permute - rearranges the dimensions of a taget tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, (2, 0, 1)) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 9592
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(9592.), tensor(9592.))

## Indexing (selcting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Index on most inner bracket (last dim)
x[0][2][2]

tensor(9)

In [ ]:
# Can also use ":" to selct "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a populat scientific Python numerical computing lib
and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to Numpy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy to pytorch, pytorch reflects numpy's default dtype as float64, unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy change
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to numpy array?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibilty (trying to take random out of random)

How a neural network learns:

`start w/ random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> ...`

To reduce the randomness in neural networks, PyTorch comes with the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

https://pytorch.org/docs/stable/notes/randomness.html?highlight=reproducibility

In [ ]:
# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9104, 0.9410, 0.7346, 0.1303],
        [0.4141, 0.8332, 0.8407, 0.9333],
        [0.9218, 0.9905, 0.0906, 0.1029]])
tensor([[0.7037, 0.2069, 0.5218, 0.6049],
        [0.4744, 0.3005, 0.3253, 0.7211],
        [0.1841, 0.3248, 0.4923, 0.9975]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
RANDOM_SEED = 69

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])
tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making fatser computations)

GPU = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch behind the scenes

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - takes little bit of setup and requires a good GPU
3. Use cloud computing - AWS, GCP, Azure

For 2 and 3 PyTorch + GPU drivers (CUDA) refer to PyTorch setup documentation:
https://pytorch.org/get-started/locally/


In [ ]:
!nvidia-smi

Sun Jul 30 03:59:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU w/ PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code  Check https://pytorch.org/docs/stable/notes/cuda.html#best-practices
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

Using a GPU results in faster computations

In [ ]:
# Create a tensor (default is on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)

print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


### 4.  Moving back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy() will Error!!!
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
## Exercies & Extra-curriculum